deps:
	rebar3 deps

compile:
	rebar3 compile

release:
	rebar3 release

clean:
	rebar3 clean

clean-all: clean
	rm -Rvf _build

tree:
	rebar3 tree

run:
	_build/default/rel/collatz/bin/collatz console

