PROJECT = eventteller
 
DEPS = cowboy erlydtl eunit_formatters eventmanager

dep_eventmanager = git http://eaict.technologiecampusdiepenbeek.be/gitblit/r/erlang1415/eventmanager.git master
 
include erlang.mk

